### ISSUE TITLE
update docker.md

### ISSUE THREAD

**Issue by NL-TCH** [RaspAP/raspap-docs#6]
Hi bill,

as discussed in raspap/raspap-docker the repo version of docker is very old on debian.
Please update the docker.md to use https://get.docker.com this is required for the composeV3.8 

Gr. TCH

**Comment by billz** [comment]
Thanks for catching this. Can you point to a specific line in the doc?

**Comment by NL-TCH** [comment]
file: [/docs/docker.md](https://github.com/RaspAP/raspap-docs/blob/master/docs/docker.md)

remove the whole "Install using the apt repository" and replace with a whole new chapter "Install using the docker unattended installation script"

:)

**Comment by billz** [comment]
Aha, looking at the get.docker.com script source, it appears the same steps are performed as in [the official docs](https://docs.docker.com/engine/install/debian/) (which this page uses).

I'm all for simplicity, so agree it makes sense to use the unattended script.
